In [1]:
from keras.models import load_model

SENET = load_model("C:\\development\\NDSC_junior\\\SRP\models\\" + "SENET")
SENET.load_weights("C:\\development\\NDSC_junior\\SRP\\weights\\senet\\weights-improvement-16-0.00.hdf5")
VGG = load_model("C:\\development\\NDSC_junior\\\SRP\models\\" + "vgg16")
VGG.load_weights("C:\\development\\NDSC_junior\\SRP\\weights\\vgg16\\weights-improvement-09-0.09.hdf5")


Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


C:\development\Anaconda3\envs\berrytensor\lib\site-packages\keras\engine\saving.py:327: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '


In [4]:
RESNET = load_model("C:\\development\\NDSC_junior\\\SRP\models\\RESNET50")
RESNET.load_weights("C:\\development\\NDSC_junior\\SRP\\weights\\resnet50\\weights-improvement-12-0.00.hdf5")


import os
import numpy as np
from keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications.resnet50 import preprocess_input




#Prepare Test Data
path = "C:\\development\\NDSC_junior\\SRP\\data\\"
x_test=[]
y_test=[]
person_folders=os.listdir(path+'\\test2')
for i,person in enumerate(person_folders):
    image_names=os.listdir(path + 'test2\\'+person+'\\')
    for image_name in image_names:
        img=load_img(path+"\\test2\\"+person+'\\'+image_name,target_size=(224,224))
        img=img_to_array(img)
        img=np.expand_dims(img,axis=0)
        img=preprocess_input(img)
        img_encode=model(img)
        x_test.append(np.squeeze(K.eval(img_encode)).tolist())
        y_test.append(i)

In [78]:
x_test=[]
y_test=[]
person_folders=os.listdir(path+'\\test2')
for i,person in enumerate(person_folders):
    image_names=os.listdir(path + 'test2\\'+person+'\\')
    for image_name in image_names:
        img=load_img(path+"\\test2\\"+person+'\\'+image_name,target_size=(224,224))
        img=img_to_array(img)
        img=np.expand_dims(img,axis=0)
        img=preprocess_input(img)
        x_test.append(img)
        y_test.append(i)

In [95]:
i = 2

In [96]:
print(RESNET.predict(x_test[i]))

[[0. 0. 0. 0. 1.]]


In [97]:
print(VGG.predict(x_test[i]))

[[0. 0. 1. 0. 0.]]


In [98]:
print(SENET.predict(x_test[i]))

[[0. 1. 0. 0. 0.]]
